# Generated by Django 3.2.8 on 2021-11-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('Latitude', models.DecimalField(decimal_places=10, max_digits=13, null=True)),
                ('Longitude', models.DecimalField(decimal_places=10, max_digits=13, null=True)),
            ],
            options={
                'db_table': 'sights',
            },
        ),
    ]
